# Generated by Django 4.2 on 2023-12-02 09:46

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=14, verbose_name='Telefoni')),
                ('instagram', models.CharField(blank=True, max_length=318, null=True, verbose_name='instagramlink')),
                ('linkedin', models.CharField(blank=True, max_length=318, null=True, verbose_name='linkedinlink')),
                ('github', models.CharField(blank=True, max_length=155, null=True, verbose_name='githublink')),
                ('birthday', models.CharField(blank=True, max_length=15, null=True)),
                ('telegram', models.CharField(blank=True, max_length=255, null=True, verbose_name='telegram url manzili')),
                ('img', models.ImageField(blank=True, null=True, upload_to='user_images')),
                ('ok', models.BooleanField(blank=True, default=False, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55, verbose_name='mijoz ismi ')),
                ('last_name', models.CharField(max_length=55, verbose_name='mijoz familyasi ')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('message', models.TextField(verbose_name='habar matni ')),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'contactlar',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='master_images')),
                ('name', models.CharField(max_length=55, verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='MasterLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50, verbose_name='masterni darajasi ')),
            ],
        ),
        migrations.CreateModel(
            name='Sped_resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='name')),
                ('phone', models.CharField(max_length=55, verbose_name='phone')),
                ('email', models.CharField(max_length=155, verbose_name='email')),
                ('addres', models.CharField(max_length=155, verbose_name='addres')),
                ('birthday', models.DateField()),
                ('education', models.CharField(max_length=155, verbose_name='unversitet')),
                ('skills', models.TextField(verbose_name='Konikma')),
                ('experience', models.TextField(verbose_name='Tajriba')),
                ('hobbies', models.CharField(max_length=500, verbose_name='qiziqish')),
                ('about', models.TextField(verbose_name='about')),
            ],
        ),
        migrations.CreateModel(
            name='Yonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=155, verbose_name='texnalogiya nomi ')),
                ('percentage', models.PositiveIntegerField(default=0, verbose_name='bilim darajasi   maximum 100 ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=55)),
                ('name', models.CharField(max_length=55, verbose_name='hizmat turi ')),
                ('text', models.TextField(verbose_name='batafsil malumot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addres', models.CharField(blank=True, max_length=255, null=True, verbose_name='addres')),
                ('education', models.CharField(blank=True, max_length=255, null=True, verbose_name='unversitet')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='Konikma')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='Tajriba')),
                ('hobbies', models.CharField(blank=True, max_length=500, null=True, verbose_name='qiziqish')),
                ('about', models.TextField(blank=True, null=True, verbose_name='about')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images', verbose_name='poroject rasmi')),
                ('name', models.CharField(max_length=55)),
                ('title', models.TextField()),
                ('github', models.CharField(blank=True, max_length=255, null=True, verbose_name='url manzili  gitgub manzili')),
                ('live_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='live preview manzili')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='masters', to='main.master'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='masterlevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='masterlevel', to='main.masterlevel'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
